// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDefaultConfig():Promise<main.DefaultConfig>;

export function ResolveDomain(arg1:string):Promise<string>;

export function StartTest(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function StopTest():Promise<void>;
