// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function PauseTest() {
  return window['go']['main']['App']['PauseTest']();
}

export function ResolveDomain(arg1) {
  return window['go']['main']['App']['ResolveDomain'](arg1);
}

export function StartTest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartTest'](arg1, arg2, arg3, arg4, arg5);
}

export function StopTest() {
  return window['go']['main']['App']['StopTest']();
}
